# Site settings
book_author: Roger C. Davis
book_title: Wall Street's Just Not That Into you

title: Roger C. Davis — Wall Street's Just Not That Into you
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  In his new book, Roger Davis tells his readers point-blank that Wall Street’s Just
  Not That Into You. Drawing on an investment career spanning more than two decades,
  Davis delivers a dynamic and deadly accurate analysis of Wall Street’s
  “one-size-fits-all” approach—and why even wealthy investors should be wary.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
